/**
 * Build Timestamp
 * 
 * This file is automatically generated at build time by scripts/generate-build-timestamp.js
 * DO NOT manually edit this file - it will be overwritten on each build.
 */

export const BUILD_TIMESTAMP = '2025-12-03T06:54:42.135Z';
export const BUILD_TIMESTAMP_FORMATTED = '2025-12-03 06:54:42 UTC';
