/**
 * Build Timestamp
 * 
 * This file is automatically generated at build time by scripts/generate-build-timestamp.js
 * DO NOT manually edit this file - it will be overwritten on each build.
 */

export const BUILD_TIMESTAMP = '2025-12-04T00:14:09.438Z';
export const BUILD_TIMESTAMP_FORMATTED = '2025-12-04 00:14:09 UTC';
