/**
 * Build Timestamp
 * 
 * This file is automatically generated at build time by scripts/generate-build-timestamp.js
 * DO NOT manually edit this file - it will be overwritten on each build.
 */

export const BUILD_TIMESTAMP = '2025-12-06T18:37:50.109Z';
export const BUILD_TIMESTAMP_FORMATTED = '2025-12-06 18:37:50 UTC';
